### ISSUE TITLE
WiFi manager getScanResults never include the created "KD-" ones

### ISSUE THREAD

**Issue by hanilozmen** [pmbento/karmadetector#2]
Hi,

First of all thanks for the application,

I tried the app but 
List<ScanResult> l = wifiManager.getScanResults();
this never returns a created "KD" network, so my app never catchs an attack. I tested it with Android 5.0 Zenfone and Android 6 General Mobile 4g. Is there anything that I missed? 

Thanks

**Comment by pmbento** [comment]
Hi,

The app creates a fake "KD-randomSomething" network profile when it starts. Since it's a manual added wireless profile, Android regularly scans for manual added networks. If you get this network on the "wifiManager.getScanResults()", then something is not right because that network shouldn't exist, and someone's probably doing a Wireless Karma Attack. That's when the app will alert you.

If you want to test the app, you can try to fire up Kali Linux which already includes the necessary tools. Here is something to get you started:
- https://www.offensive-security.com/kali-linux/kali-linux-evil-wireless-access-point/
- https://github.com/sensepost/mana

Waiting for you feedback.
